// Given a list of different attributes between each pari of characters:

// [Easy] Find all pairs of characters that differ by only one attribute

// [Medium] Write a function that takes two characters and produces an object
// of shared attributes. (eg. combine("Tom", "Susan") = { wearingHat: true })

// [Hard] Create a tree of groupings where each leaf node is a character and
// any parent node is generated by the combine function. At the top of the tree
// should be a node that has doesn't have any shared attributes.
